services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gymtracker_frontend
    ports:
      - "6500:6500" # Host and container both use 6500
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # prevent overwriting container node_modules
    stdin_open: true
    tty: true
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge
